// Generated by CoffeeScript 1.6.3
(function() {
  define(['module', 'cs!srndp_settings'], function(module, Settings) {
    var _Utils;
    return _Utils = {
      logging: Settings.logging,
      parseToObj: function(s) {
        var keyval, obj, pair, pairs, _i, _len;
        obj = {};
        pairs = s.split("&");
        if (pairs != null) {
          for (_i = 0, _len = pairs.length; _i < _len; _i++) {
            pair = pairs[_i];
            keyval = pair.split("=");
            if (keyval.length === 2) {
              obj[keyval[0]] = keyval[1];
            }
          }
        }
        return obj;
      },
      eliminateHashPart: function() {
        var hashPosition, href, urlToPreserve;
        href = document.location.href;
        hashPosition = href.indexOf("#");
        if (hashPosition !== -1) {
          urlToPreserve = href.substring(0, hashPosition);
          return window.history.pushState({
            "pageTitle": document.title
          }, "", urlToPreserve);
        }
      },
      log: function(msg) {
        if (this.logging) {
          return console.log(msg);
        }
      }
    };
  });

}).call(this);
