// Generated by CoffeeScript 1.6.3
(function() {
  define(['cs!srndp_utils', 'cs!srndp_settings', 'cs!srndp_auth', 'facebook_sdk', 'jquery.cookie'], function(_Utils, Settings, Auth, _1, _2) {
    var replyMsg, session;
    window.fbAsyncInit = function() {
      FB.init({
        appId: Settings.FB_APP_ID,
        channelUrl: Settings.BASE_URL + '/public/website/channel.html',
        status: true
      });
      return FB.Event.subscribe('auth.statusChange', function(response) {
        if ((window.__SRNDP__ORIGIN_ != null)) {
          _Utils.log(response);
          return parent.postMessage(JSON.stringify(response), window.__SRNDP__ORIGIN_);
        }
      });
    };
    window.onmessage = function(msg) {
      var clientId;
      if (msg.origin === window.__SRNDP__ORIGIN_) {
        if (msg.data.indexOf("srndp-init") !== -1) {
          _Utils.log("srndp-init");
          clientId = msg.data.substring(11);
          return this.CLIENT_ID = clientId;
        } else {
          switch (msg.data) {
            case "srndp-logout-fb":
              return FB.logout();
            case "srndp-login-srndp":
              return Auth.loginFromIframe("serendip", this.CLIENT_ID, true).done(function(res) {
                var replyMsg;
                replyMsg = JSON.stringify(res);
                _Utils.log("srndp-login-success:" + replyMsg);
                return parent.postMessage("srndp-login-success:" + replyMsg, window.__SRNDP__ORIGIN_);
              }).fail(function() {
                _Utils.log("srndp-login-failed");
                return parent.postMessage("srndp-login-failed", window.__SRNDP__ORIGIN_);
              });
          }
        }
      }
    };
    window.SRNDP = {};
    parent.postMessage("srndp-ready", window.__SRNDP__ORIGIN_);
    _Utils.log("srndp-ready");
    session = $srndp.cookie(Settings.SESSION_COOKIE_NAME);
    if (session != null) {
      session = session.indexOf('user');
    } else {
      session = -1;
    }
    replyMsg = session === -1 ? "logged_out" : "logged_in";
    parent.postMessage("srndp-chk-session:" + replyMsg, window.__SRNDP__ORIGIN_);
    return _Utils.log("srndp-chk-session:" + replyMsg);
  });

}).call(this);
