// Generated by CoffeeScript 1.6.3
(function() {
  define(['cs!srndp_utils', 'cs!srndp_settings', 'cs!srndp_auth', 'facebook_sdk', 'jquery.cookie'], function(_Utils, Settings, Auth, _1, _2) {
    var replyMsg, session;
    window.fbAsyncInit = function() {
      FB.init({
        appId: Settings.FB_APP_ID,
        channelUrl: Settings.BASE_URL + '/public/website/channel.html',
        status: true
      });
      return FB.Event.subscribe('auth.statusChange', function(response) {
        if ((window.__SRNDP__ORIGIN_ != null)) {
          _Utils.log(response);
          return parent.postMessage(JSON.stringify(response), window.__SRNDP__ORIGIN_);
        }
      });
    };
    window.SRNDP = {};
    parent.postMessage("srndp-ready", window.__SRNDP__ORIGIN_);
    _Utils.log("srndp-ready");
    session = $.cookie(Settings.SESSION_COOKIE_NAME);
    if (session != null) {
      session = session.indexOf('user');
    } else {
      session = -1;
    }
    replyMsg = session === -1 ? "logged_out" : "logged_in";
    parent.postMessage("srndp-chk-session:" + replyMsg, window.__SRNDP__ORIGIN_);
    return _Utils.log("srndp-chk-session:" + replyMsg);
  });

}).call(this);
